//
//  Radon.swift
//  Radon
//
//  Automatically generated by Radonon 16/12/2024.
//  See http://github.com/e-sites/Radon for more information.
//

import Foundation

public class Radon {
    nonisolated(unsafe) public static var defaultPluralLocale = Locale.current

    private init() { }
}