//
//  Radon.swift
//  Radon
//
//  Automatically generated by Radonon 16/12/2024.
//  See http://github.com/e-sites/Radon for more information.
//

#if os(OSX)
public typealias RadonColor = NSColor
import AppKit
#else
public typealias RadonColor = UIColor
import UIKit
#endif

private func color(named name: String) -> RadonColor {
    return RadonColor(named: name, in: Bundle.main, compatibleWith: nil)!
}

extension Radon {
    public enum `assets` {
        public enum `colors` {
            public enum `background` {
                public static var `backgroundCardHighlighted`: RadonColor { return color(named: "Background-Card-Highlighted") }
                public static var `backgroundCard`: RadonColor { return color(named: "Background-Card") }
                public static var `backgroundDefault`: RadonColor { return color(named: "Background-Default") }
            }
            public enum `card` {
                public static var `cardBorder`: RadonColor { return color(named: "Card-Border") }
            }
            public enum `checkbox` {
                public static var `checkboxActive`: RadonColor { return color(named: "Checkbox-Active") }
                public static var `checkboxBorder`: RadonColor { return color(named: "Checkbox-Border") }
            }
            public enum `state` {
                public static var `stateError`: RadonColor { return color(named: "State-Error") }
                public static var `stateSuccess`: RadonColor { return color(named: "State-Success") }
                public static var `stateWarning`: RadonColor { return color(named: "State-Warning") }
            }
            public enum `text` {
                public static var `textGray`: RadonColor { return color(named: "Text-Gray") }
                public static var `textPrimaryLight`: RadonColor { return color(named: "Text-Primary-Light") }
                public static var `textPrimary`: RadonColor { return color(named: "Text-Primary") }
            }
            public enum `textField` {
                public static var `textFieldBorderFocussed`: RadonColor { return color(named: "TextField-Border-Focussed") }
                public static var `textFieldBorder`: RadonColor { return color(named: "TextField-Border") }
            }
            public enum `theme` {
                public static var `themePink`: RadonColor { return color(named: "Theme-Pink") }
                public static var `themePrimary`: RadonColor { return color(named: "Theme-Primary") }
                public static var `themeSecondary`: RadonColor { return color(named: "Theme-Secondary") }
                public static var `themeYellow`: RadonColor { return color(named: "Theme-Yellow") }
            }
            public static var `disabled`: RadonColor { return color(named: "Disabled") }
            public static var `divider`: RadonColor { return color(named: "Divider") }
            public static var `skeleton`: RadonColor { return color(named: "Skeleton") }
        }
    }
}