//
//  Radon.swift
//  Radon
//
//  Automatically generated by Radon on 13/07/2018.
//  See http://github.com/e-sites/Radon for more information
//

import UIKit

public extension Radon {
    public struct images {
        private init() { }

        public struct images {
            private init() { }

            public struct emptyFolder {
                private init() { }

            }

            public static var handWater: UIImage { return UIImage(named: "hand-water")! }
            public static var heavybox: UIImage { return UIImage(named: "heavybox")! }
        }

        public struct assets {
            private init() { }

            public struct backgrounds {
                private init() { }

                public static var sandyBoots: UIImage { return UIImage(named: "sandy-boots")! }
                public static var someBoat: UIImage { return UIImage(named: "some&&boat")! }
                public static var planeWing: UIImage { return UIImage(named: "plane wing")! }
                public static var tree: UIImage { return UIImage(named: "tree")! }
                public static var _1Cyclists: UIImage { return UIImage(named: "1cyclists")! }
            }

            public struct icons {
                private init() { }

                public static var ironMan: UIImage { return UIImage(named: "ironMan")! }
                public static var unicorn: UIImage { return UIImage(named: "unicorn")! }
            }

        }

    }

}