//
//  Radon.swift
//  Radon
//
//  Automatically generated by Radonon 16/12/2024.
//  See http://github.com/e-sites/Radon for more information.
//

import Foundation

extension Radon {

    public enum strings {
        public enum `a` {
            public enum `_1very` {
                public enum `deep` {
                    public enum `nested` {
                        public enum `key` {
                            public static var `example`: String { NSLocalizedString("a_1very_deep_nested_key_example", bundle: Bundle.main, comment: "") }

                        }
                    }
                }
            }
        }
        public enum `about` {
            public static var `name`: String { NSLocalizedString("about_name", bundle: Bundle.main, comment: "") }

        }
        public static func `apple`(_ count: Int, locale: Locale = Radon.defaultPluralLocale) -> String { String(format: NSLocalizedString("apple %lld", bundle: Bundle.main, comment: ""), locale: locale, count) }

        public enum `confirm` {
            public enum `city` {
                public static var `name`: String { NSLocalizedString("confirm_city_name%@", bundle: Bundle.main, comment: "") }

            }
        }
        public enum `dashboard` {
            public static var `title`: String { NSLocalizedString("dashboard_title", bundle: Bundle.main, comment: "") }

        }
        public static func `pears`(_ count: Int, locale: Locale = Radon.defaultPluralLocale) -> String { String(format: NSLocalizedString("pears %lld", bundle: Bundle.main, comment: ""), locale: locale, count) }

        public enum `settings` {
            public enum `personal` {
                public static var `title`: String { NSLocalizedString("settings_personal_title", bundle: Bundle.main, comment: "") }

            }
            public static var `title`: String { NSLocalizedString("settings_title", bundle: Bundle.main, comment: "") }

        }
        public enum `somekey` {
            public enum `override` {
                public static var `value`: String { NSLocalizedString("somekey_override", bundle: Bundle.main, comment: "") }

                public static var `stuff`: String { NSLocalizedString("somekey_override_stuff", bundle: Bundle.main, comment: "") }

            }
        }
        public static var `yes`: String { NSLocalizedString("yes", bundle: Bundle.main, comment: "") }

    }
}