//
//  Generator.swift
//  Radon
//
//  Created by Bas van Kuijck on 12/07/2018.
//

import Foundation

protocol Generator {
    var name: String { get }
    var allowedExtensions: [String] { get }
    func parse(folder: Folder)

    init(outputFolder: String)
}


extension Generator {
    func headerLines(fileName: String) -> String {
        let dateFormatter = DateFormatter()
        dateFormatter.dateStyle = .short
        let date = dateFormatter.string(from: Date())
        return [
            "//",
            "//  \(fileName).swift",
            "//  Radon",
            "//",
            "//  Automatically generated by Radon on \(date).",
            "//  See http://github.com/e-sites/Radon for more information.",
            "//",
            ""
        ].joined(separator: "\n")
    }
}
